version: '3' # version of docker-compose
networks:
    publisherNet:
    subscribeNet:
services:
    publisher:
        image: python:3.6
        volumes: 
            - ./publisher:/app
            - ./data:/data
            - ./config:/config
        working_dir: /app
        command:  ./pub.sh
        networks:
            - publisherNet
        depends_on: 
            - subscriber        
    subscriber:
        image: python:3.6
        volumes: 
            - ./subscriber:/app
            - ./data:/data
            - ./config:/config
        working_dir: /app
        command:  ./sub.sh
        networks:
            - subscribeNet
        