version: '3' # version of docker-compose
networks:
    publisherNet:
    subscribeNet:
services:
    publisher:
        image: python:3.7-alpine
        volumes: 
            - ./publisher:/app
        working_dir: /app
        command:  ./pub.sh
        networks:
            - publisherNet    
    subscribe:
        image: python:3.7-alpine
        volumes: 
            - ./subscribe:/app
        working_dir: /app
        command:  ./sub.sh
        networks:
            - subscribeNet
        